"""separate feature display text

Revision ID: 1f9de2de0722
Revises: 10a9db7d27fc
Create Date: 2021-03-20 17:21:07.801229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9de2de0722'
down_revision = '10a9db7d27fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('featured', sa.Column('display', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('featured', 'display')
    # ### end Alembic commands ###
