"""empty message

Revision ID: 5390577ddf3c
Revises: a4f30b54d366
Create Date: 2021-03-17 05:50:50.137057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5390577ddf3c'
down_revision = 'a4f30b54d366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('featured_img', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'featured_img')
    # ### end Alembic commands ###
