"""empty message

Revision ID: a4f30b54d366
Revises: d4bc0e5fdbbd
Create Date: 2021-03-11 06:23:58.321691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f30b54d366'
down_revision = 'd4bc0e5fdbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_post_slug'), 'post', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_slug'), table_name='post')
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###
