"""draft or publish

Revision ID: ad106249fbf4
Revises: 5390577ddf3c
Create Date: 2021-03-17 21:22:16.404154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad106249fbf4'
down_revision = '5390577ddf3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'status')
    # ### end Alembic commands ###
